apiVersion: v2
name: events
description: Observe kubernetes event collection
type: application
version: 0.1.11
appVersion: v0.9.1
dependencies:
  - name: endpoint
    version: 0.1.6
    repository: file://../endpoint
maintainers:
  - name: Observe
    email: support@observeinc.com
