apiVersion: v2
name: events
description: DEPRECATED Observe kubernetes event collection
type: application
version: 0.6.0
deprecated: true
appVersion: v0.11.6
dependencies:
  - name: endpoint
    version: 0.1.13
    repository: file://../endpoint
