apiVersion: v2
name: metrics
description: Observe metrics collection
type: application
version: 0.2.0
dependencies:
  - name: grafana-agent
    version: 0.10.0
    repository: https://grafana.github.io/helm-charts
  - name: endpoint
    version: 0.1.3
    repository: file://../endpoint
maintainers:
  - name: Observe
    email: support@observeinc.com
