{{ if .Values.gatewayDeployment.enabled  -}}
{{- include "observe-agent.validateOtelPodUid" (dict "componentName" "gateway" "extraEnvs" (index .Values "gateway" "extraEnvs") "fleetEnabled" .Values.agent.config.global.fleet.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: {{ template "observe-agent.namespace" . }}
data:
  relay: |
      {{- include "observe.deployment.applyGatewayConfig" . | nindent 4 -}}
{{ end -}}
