global:
  observe:
    collectionEndpoint: ""

    # Legacy configuration values, only used if collectionEndpoint is not set
    customer: ""
    collectorScheme: "https"
    collectorHost: "collect.observeinc.com"
    collectorPort: "443"
