---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-events.fullname" . }}
  labels:
    {{- include "kube-events.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-events.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-events.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {key: observeinc.com/unschedulable, operator: DoesNotExist}
                  - {key: kubernetes.io/os, operator: NotIn, values: [windows]}
      serviceAccountName: {{ include "kube-events.serviceAccountName" . }}
      initContainers:
        - name: kube-cluster-info
          image: {{ .Values.image.kube_cluster_info.repository }}:{{ default .Chart.AppVersion .Values.image.kube_cluster_info.tag }}
          imagePullPolicy: {{ .Values.image.kube_cluster_info.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      containers:
        - name: kube-state-events
          image: {{ .Values.image.kube_state_events.repository }}:{{ default .Chart.AppVersion .Values.image.kube_state_events.tag }}
          imagePullPolicy: {{ .Values.image.kube_state_events.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.image.kube_state_events.command }}
          command: {{- range .Values.image.kube_state_events.command }}
          - {{ . }}
          {{- end }}
          {{- end }}
          {{- if .Values.image.kube_state_events.args }}
          args: {{- range .Values.image.kube_state_events.args }}
          - {{ . }}
          {{- end }}
          {{- else }}
          args:
            - -healthz-addr=:5171
            - -metrics-addr=:9090
            - -o={{ include "observe.collectionEndpointWithToken" . }}/v1/http/kubernetes/events?clusterUid=$(OBSERVE_CLUSTER)
            - v1
            - apps/v1
            - autoscaling/v1
            - batch/v1
            - networking.k8s.io/v1
          {{- end}}
          ports:
            - containerPort: 5171
            - containerPort: 9090
              name: http-metrics
          env:
            - name: OBSERVE_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: id
            {{- range .Values.extraEnv }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: credentials
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5171
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5171
            timeoutSeconds: 5
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
